Completion stat
saltastro/tacprocess pull request #102
Opened 2019-06-28 13:21 UTC by chynamyerz

2019-06-28 15:47 UTC, hettlage requested changes
> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: all files reviewed, 11 unresolved discussions (waiting on @chynamyerz)

___
*[src/api/graphQL.js, line 380 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTbEGJ69228sKg5nrD:-LiTbEGJ69228sKg5nrE:b-n95vev) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/api/graphQL.js#L380)):*
> ```JavaScript
>     }
>     `
>   if (process.env.NODE_ENV === 'development'){
> ```

Why do you have to distinguish between dev and production?
___
*[src/reducers/partnerShareTimes.js, line 48 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTcqBlAFPiQWXi15uQ:-LiTcqBlAFPiQWXi15uR:bmy9p4c) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/reducers/partnerShareTimes.js#L48)):*
> ```JavaScript
>           fetchingError: null
>         },
>         partnerShareTimes: action.payload.partnerShareTimes,
> ```

What is the difference between partnerShareTimes abs initPartnerShareTimes?
___
*[src/util/index.js, line 423 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTdf6q-KXhW74oKecK:-LiTdf6q-KXhW74oKecL:b-qne31) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/index.js#L423)):*
> ```JavaScript
> }
> 
> export function currentSemester () {
> ```

The calculation seems to be incorrect.
___
*[src/util/partner-stat.js, line 19 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTdtk8B9orvuHidMH0:-LiTdtk8B9orvuHidMH1:b-x0ioi8) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L19)):*
> ```JavaScript
>   }
>   const percentage = (dividend / divisor) * 100
>   return percentage.toFixed(2)
> ```

I'd rather not include a toFixed here. But if you do,  you should document it.
___
*[src/util/partner-stat.js, line 128 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTewc8A8qYi9fLyPwe:-LiTewc8A8qYi9fLyPwf:bra6sp5) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L128)):*
> ```JavaScript
>   if (partnerCode === 'All') {
>     // according to the time allocated for the semester
>     timeAllocations = timeAllocations.filter(t => (t.semester === semester)) || []
> ```

Why the "|| []"?
___
*[src/util/partner-stat.js, line 152 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTfSoL6-WQmRQPctgh:-LiTfSoL6-WQmRQPctgi:b-al8j6j) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L152)):*
> ```JavaScript
>   const allocatedTime = (allocatedTimeP0 + allocatedTimeP1 + allocatedTimeP2 + (allocatedTimeP3 / 3))
> 
>   // calculating the total observed time
> ```

I don't think you would divide the observed P3 by 3.

Also, you might consider replacing "observation" with "observedTime" in the variable names.
___
*[src/util/partner-stat.js, line 162 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiThsCdCX11LykaZnQ0:-LiThsCdCX11LykaZnQ1:b-l4gzng) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L162)):*
> ```JavaScript
> 
> /**
>  * A function for calculating the observed time per partner
> ```

Maybe add that all the quantities are for one proposal?
___
*[src/util/partner-stat.js, line 229 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTj7zdEDtoOeHm6H-V:-LiTj7zdEDtoOeHm6H-W:bymom0w) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L229)):*
> ```JavaScript
> 
>     // filter the time allocated by partner
>     const p0p1PartnerTimeAllocations = p0p1TimeAllocations.filter((t) => t.partnerCode === partnerCode)
> ```

Don't you have to filter these by semester?
___
*[src/util/partner-stat.js, line 258 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTkd6x3xwlekXoSutr:-LiTkd6x3xwlekXoSuts:b-t3gkf8) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L258)):*
> ```JavaScript
> 
>   // calculating the total allocated time for the partner
>   const totalAllocated = p0p1Allocated + p2Allocated + p3Allocated
> ```

I think p3Allocated has to be divided by 3?
___
*[src/util/partner-stat.js, line 280 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTl-cv1h4WRxwd0F_Y:-LiTl-cv1h4WRxwd0F_Z:b-t3gkf8) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L280)):*
> ```JavaScript
>       p0p1: calculatePercentage(p0p1Observed, p0p1Allocated),
>       p2: calculatePercentage(p2Observed, p2Allocated),
>       p3: calculatePercentage(p3Observed, p3Allocated),
> ```

I think p3Allocated has to be divided by 3?
___
*[src/util/partner-stat.js, line 281 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTl1IvAYjWmkYLkGbe:-LiTl1IvAYjWmkYLkGbf:b-ib3q0n) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L281)):*
> ```JavaScript
>       p2: calculatePercentage(p2Observed, p2Allocated),
>       p3: calculatePercentage(p3Observed, p3Allocated),
>       total: calculatePercentage(totalObserved, (totalAllocated / 1.5))
> ```

Why the division by 1.5?


<!-- Sent from Reviewable.io -->

2019-07-01 10:47 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: 20 of 23 files reviewed, 11 unresolved discussions (waiting on @chynamyerz and @hettlage)

___
*[src/api/graphQL.js, line 380 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTbEGJ69228sKg5nrD:-LigbQJ-DUEiqtw9pXGS:bvo4ar7) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/api/graphQL.js#L380)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you have to distinguish between dev and production?
</blockquote></details>

This was supposed to be removed as it handles two API servers on my localhost.
___
*[src/reducers/partnerShareTimes.js, line 48 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTcqBlAFPiQWXi15uQ:-LigeJQ92HeQi0FdHv4y:bout4n0) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/reducers/partnerShareTimes.js#L48)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

What is the difference between partnerShareTimes abs initPartnerShareTimes?
</blockquote></details>

Really there is no difference. Removed
___
*[src/util/index.js, line 423 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTdf6q-KXhW74oKecK:-Lih1Gjx36n7vCESOMfn:b-tzwb59) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/index.js#L423)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The calculation seems to be incorrect.
</blockquote></details>

Fixed, thanks for the help.
___
*[src/util/partner-stat.js, line 19 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTdtk8B9orvuHidMH0:-Lih1OPB20hlZtOkW0zk:ba3dfob) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L19)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd rather not include a toFixed here. But if you do,  you should document it.
</blockquote></details>

Removed
___
*[src/util/partner-stat.js, line 128 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTewc8A8qYi9fLyPwe:-Ligvsoo7Y_q-_7A6bBu:b-2pvt0q) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L128)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the "|| []"?
</blockquote></details>

Unnecessary yes.
___
*[src/util/partner-stat.js, line 152 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTfSoL6-WQmRQPctgh:-Lih1ReLDMKZdNC4F0MG:b-m2qkjf) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L152)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you would divide the observed P3 by 3.

Also, you might consider replacing "observation" with "observedTime" in the variable names.
</blockquote></details>

Will consult with Encarni.
___
*[src/util/partner-stat.js, line 162 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiThsCdCX11LykaZnQ0:-Lih2wU_BQgJBA614ypr:bqmjwbz) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L162)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe add that all the quantities are for one proposal?
</blockquote></details>

Added
___
*[src/util/partner-stat.js, line 229 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTj7zdEDtoOeHm6H-V:-Lih4YRVBWGvfKeDpMTr:b-kb16i) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L229)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Don't you have to filter these by semester?
</blockquote></details>

It is already filtered by semester
___
*[src/util/partner-stat.js, line 280 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTl-cv1h4WRxwd0F_Y:-Lih7OY53ZYlypj7r85s:b8fw4pp) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L280)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think p3Allocated has to be divided by 3?
</blockquote></details>

Dividing by 3 gives values that are very off from the ones in the link.
___
*[src/util/partner-stat.js, line 281 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTl1IvAYjWmkYLkGbe:-Lih7yTP5_EU1J0R4J3n:b-il2lgo) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L281)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why the division by 1.5?
</blockquote></details>

Removing 1.5 also gives values that are very off. (I will have a chat with Encarni about all this)


<!-- Sent from Reviewable.io -->

2019-07-01 13:08 UTC, hettlage requested changes
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: all files reviewed, 4 unresolved discussions (waiting on @chynamyerz)

___
*[src/util/partner-stat.js, line 229 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTj7zdEDtoOeHm6H-V:-LihcST9EKHcYpc-ZR8X:b-op84wn) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L229)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

It is already filtered by semester
</blockquote></details>

Good point. :)

But maybe it might make sense to combine the filtering by semester and partner into a single filtering step?
___
*[src/util/partner-stat.js, line 258 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTkd6x3xwlekXoSutr:-LihcsvL6YEA-CSR172t:bukehf1) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L258)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think p3Allocated has to be divided by 3?
</blockquote></details>

Hmm, maybe not. Whatever you do, it is  misleading... :/
___
*[src/util/partner-stat.js, line 280 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTl-cv1h4WRxwd0F_Y:-Lihd5931QqC8mgzOPoM:b-7u8drb) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L280)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Dividing by 3 gives values that are very off from the ones in the link.
</blockquote></details>

Ah, but the question is not whether the values are different from the ones in the link, but rather whether they are correct... :)
___
*[src/util/partner-stat.js, line 281 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTl1IvAYjWmkYLkGbe:-LihdTFU9j99nq7xg4J9:bwic0s8) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L281)):*
<details><summary><i>Previously, chynamyerz wrote…</i></summary><blockquote>

Removing 1.5 also gives values that are very off. (I will have a chat with Encarni about all this)
</blockquote></details>

Okay, thanks.


<!-- Sent from Reviewable.io -->

2019-09-24 12:27 UTC, chynamyerz reviewed
New commits with a lot of changes.

> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102#-:-LpYEQHF9ZMSo6vfY9Ec:bt5o7p1)* status: 13 of 33 files reviewed, 4 unresolved discussions (waiting on @chynamyerz and @hettlage)



<!-- Sent from Reviewable.io -->

2019-10-21 12:12 UTC, hettlage requested changes
> Reviewed 20 of 20 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: all files reviewed, 16 unresolved discussions (waiting on @chynamyerz)

___
*[src/rootReducer.js, line 7 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhkrTy-0H_9mU2X0tu:-LrhkrTy-0H_9mU2X0tv:bjnrq4x) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/rootReducer.js#L7)):*
> ```JavaScript
> import proposals from './reducers/proposals'
> import partnerStatProposals from './reducers/partnerStatProposals'
> import partnerStat1Proposals from './reducers/partnerStat1Proposals'
> ```

Should be renamed
___
*[src/rootReducer.js, line 22 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhtTVsAdR0Bc6yFOE-:-LrhtTVsAdR0Bc6yFOE0:bag4ngp) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/rootReducer.js#L22)):*
> ```JavaScript
> 	proposals,
> 	partnerStatProposals,
> 	partnerStat1Proposals,
> ```

Can this be renamed?
___
*[src/types.js, line 28 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhtZHt05ziSyJ1ct4p:-LrhtZHt05ziSyJ1ct4q:b-uxysrw) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/types.js#L28)):*
> ```JavaScript
> export const SUBMIT_PARTNER_STAT_COMMENT_PASS = 'SUBMIT_PARTNER_STAT_COMMENT_PASS'
> 
> export const FETCH_PARTNER_STAT1_PROPOSALS_PASS = 'FETCH_PARTNER_STAT1_PROPOSALS_PASS'
> ```

Can these be renamed/
___
*[src/types.js, line 38 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lrhu2VM4ymzE7F3Clgl:-Lrhu2VM4ymzE7F3Clgm:b-8e3foh) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/types.js#L38)):*
> ```JavaScript
> export const FETCH_PARTNER_SHARE_TIMES_START = 'FETCH_PARTNER_SHARE_TIMES_START'
> 
> export const FETCH_WEATHER_DOWN_TIME_START = 'FETCH_WEATHER_DOWN_TIME_START'
> ```

Should be renamed. (You are fetching more than the weather downtime.)
___
*[src/components/plots/TimeBreakdownDistribution.js, line 36 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhzPw6-oWClZqTR7M2:-LrhzPw76LztqINFo0b5:b-hul0cu) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/plots/TimeBreakdownDistribution.js#L36)):*
> ```JavaScript
>     datasets={ dataset }
>     xLabel='Weather'
>     yLabel='Down Time (hrs)'/>
> ```

Downtime is a bit misleading as science time isn't downtime.
___
*[src/components/tables/ObservationTable.js, line 21 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri6whGC1fQ2ju4GdoD:-Lri6whHCLln3HQEb7yh:bi0ovjr) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/ObservationTable.js#L21)):*
> ```JavaScript
>         <th>Priority</th>
>         <th>Observed / Allocated Time (sec)</th>
>         <th>Remained Time (sec)</th>
> ```

Remained ---> Remaining
___
*[src/components/tables/ObservationTable.js, line 22 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri7dQ_4hHnEzrsvleO:-Lri7dQ_4hHnEzrsvleP:bvqrj77) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/ObservationTable.js#L22)):*
> ```JavaScript
>         <th>Observed / Allocated Time (sec)</th>
>         <th>Remained Time (sec)</th>
>         <th>Percentage</th>
> ```

Percentage of what?
___
*[src/components/tables/PartnerStatTable.js, line 50 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri-B5f5aW90Mr2lNbH:-Lri-B5f5aW90Mr2lNbI:bttvc4f) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/PartnerStatTable.js#L50)):*
> ```JavaScript
>                 )
>               } else if(proposalAstronomer === selectedLiaison) {
>                 return (
> ```

Isn't that the same as the return value for the previous condition?
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 11 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri-whZ2lNhF5ILMond:-Lri-whZ2lNhF5ILMone:bzi7vx5) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L11)):*
> ```JavaScript
> function setSeeing(proposals, partner) {
>   const maxSeeing =  {
>     less15: {
> ```

The property names might be a bit problematic.
___
*[src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js, line 9 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri0w2p-QEhuqbizy-q:-Lri0w2p-QEhuqbizy-r:b-qkdltm) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js#L9)):*
> ```JavaScript
>       <thead>
>         <tr>
>           <th>Condition</th>
> ```

Maybe "Category" rather than "Condition"?
___
*[src/components/tables/tablesComponents/ObservationTableRow.js, line 10 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri1FHNA0ncL3_KsdwW:-Lri1FHNA0ncL3_KsdwX:bb9s0ra) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/tablesComponents/ObservationTableRow.js#L10)):*
> ```JavaScript
>       <td>P{ observation.priority }</td>
>       <td>{ observation.observedTime } / { observation.allocatedTime }</td>
>       <td>{ observation.allocatedTime ? observation.remainder : 'Nan' }</td>
> ```

"NaN" is maybe a bit of developer lingo, and "n/a" or "undefined" might be clearer.
___
*[src/components/tables/tablesComponents/ObservationTableRow.js, line 11 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri2zFC33nTa-LF_Eo4:-Lri2zFC33nTa-LF_Eo5:b4z2ti9) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/tablesComponents/ObservationTableRow.js#L11)):*
> ```JavaScript
>       <td>{ observation.observedTime } / { observation.allocatedTime }</td>
>       <td>{ observation.allocatedTime ? observation.remainder : 'Nan' }</td>
>       <td>{ observation.allocatedTime ? observation.percentage : 'Nan' }{observation.allocatedTime ? '%' : ''}</td>
> ```

Can be simplified. :)
___
*[src/util/partner-stat.js, line 280 at r2](https://reviewable.io/reviews/saltastro/tacprocess/102#-LriCSMk31CAVWQcOQ3w:-LriCSMk31CAVWQcOQ3x:bxxl528) ([raw file](https://github.com/saltastro/tacprocess/blob/f30d87bc281cfd69470e5cdab3b496ce1cc5c305/src/util/partner-stat.js#L280)):*
> ```JavaScript
>       p0p1: calculatePercentage(p0p1Observed, p0p1Allocated).toFixed(2),
>       p2: calculatePercentage(p2Observed, p2Allocated).toFixed(2),
>       p3: calculatePercentage(p3Observed, p3Allocated).toFixed(2),
> ```

That should include the factor 1/3 for P3. (Which requires making changes elsewhere, of course.)
___
*[src/util/partner-stat.js, line 80 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri4L4YCkc-igTBsyZk:-Lri4L4YCkc-igTBsyZl:bm0mdtz) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/util/partner-stat.js#L80)):*
> ```JavaScript
>   const totalObsTime = sumNumbers(observationsPriority.map((o) => o.block.length))
>   // calculating the remained allocated time
>   const remainedAllocatedTime = totalObsTime ? totalAllocTime % totalObsTime : totalAllocTime
> ```

There seems to be a flaw in the logic.

remained ---> remaining
___
*[src/util/partner-stat.js, line 268 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LriDTbr2I2HsGEVynPU:-LriDTbr2I2HsGEVynPV:baxtme1) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/util/partner-stat.js#L268)):*
> ```JavaScript
>       p0p1: p0p1Allocated,
>       p2: p2All [...]

2019-10-22 13:39 UTC, chynamyerz reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: 22 of 34 files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[src/rootReducer.js, line 7 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhkrTy-0H_9mU2X0tu:-LrnfmPJ4YNmHgqR7ylS:biyhwx1) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/rootReducer.js#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be renamed
</blockquote></details>

Decided to keep it for now.
___
*[src/rootReducer.js, line 22 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhtTVsAdR0Bc6yFOE-:-LrnftkJ1NQGxizklYm-:bjgiwn9) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/rootReducer.js#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can this be renamed?
</blockquote></details>

Decided to keep it for now.
___
*[src/types.js, line 28 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhtZHt05ziSyJ1ct4p:-LrnfwmO8mrQwbY_MVwt:biyhwx1) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/types.js#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can these be renamed/
</blockquote></details>

Decided to keep it for now.
___
*[src/types.js, line 38 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lrhu2VM4ymzE7F3Clgl:-Lrng-9d214MA2W3s-Ng:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/types.js#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should be renamed. (You are fetching more than the weather downtime.)
</blockquote></details>

Done.
___
*[src/components/plots/TimeBreakdownDistribution.js, line 36 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LrhzPw6-oWClZqTR7M2:-Lrng1YI-IrkRSkKJIRU:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/plots/TimeBreakdownDistribution.js#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Downtime is a bit misleading as science time isn't downtime.
</blockquote></details>

Done.
___
*[src/components/tables/ObservationTable.js, line 21 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri6whGC1fQ2ju4GdoD:-Lrng2SJ1BrVmH54P0js:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/ObservationTable.js#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Remained ---> Remaining
</blockquote></details>

Done.
___
*[src/components/tables/ObservationTable.js, line 22 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri7dQ_4hHnEzrsvleO:-Lrng39u8L59ygLf6od6:b4pr8s0) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/ObservationTable.js#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Percentage of what?
</blockquote></details>

Changed to completion
___
*[src/components/tables/PartnerStatTable.js, line 50 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri-B5f5aW90Mr2lNbH:-Lrng6rv5w0EcsgLXD-W:b-bu91xm) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/PartnerStatTable.js#L50)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't that the same as the return value for the previous condition?
</blockquote></details>

Updated
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 11 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri-whZ2lNhF5ILMond:-LrngAVW24BYS25dRHvy:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The property names might be a bit problematic.
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js, line 9 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri0w2p-QEhuqbizy-q:-LrngBYEBk8XQ7NlcB9f:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe "Category" rather than "Condition"?
</blockquote></details>

Done.
___
*[src/components/tables/tablesComponents/ObservationTableRow.js, line 10 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri1FHNA0ncL3_KsdwW:-LrngE554bahgVW1H3yC:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/tablesComponents/ObservationTableRow.js#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

"NaN" is maybe a bit of developer lingo, and "n/a" or "undefined" might be clearer.
</blockquote></details>

Done.
___
*[src/components/tables/tablesComponents/ObservationTableRow.js, line 11 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri2zFC33nTa-LF_Eo4:-LrngFbnCVzcdMs3d5rL:b-bu91xm) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/components/tables/tablesComponents/ObservationTableRow.js#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can be simplified. :)
</blockquote></details>

Updated
___
*[src/util/partner-stat.js, line 229 at r1](https://reviewable.io/reviews/saltastro/tacprocess/102#-LiTj7zdEDtoOeHm6H-V:-LrneotL0y6ZceWB1Wv5:b74y5rl) ([raw file](https://github.com/saltastro/tacprocess/blob/27c5b8b3f0449680b488cafa337b1221125b6d0b/src/util/partner-stat.js#L229)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Good point. :)

But maybe it might make sense to combine the filtering by semester and partner into a single filtering step?
</blockquote></details>

It filtered by semester and priority first, because it is used in different parts.
___
*[src/util/partner-stat.js, line 280 at r2](https://reviewable.io/reviews/saltastro/tacprocess/102#-LriCSMk31CAVWQcOQ3w:-Lrnfk-rAKb2Y_4GiZZP:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/f30d87bc281cfd69470e5cdab3b496ce1cc5c305/src/util/partner-stat.js#L280)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

That should include the factor 1/3 for P3. (Which requires making changes elsewhere, of course.)
</blockquote></details>

Done.
___
*[src/util/partner-stat.js, line 80 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-Lri4L4YCkc-igTBsyZk:-LrnelmpCBU15fw3u9hx:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/util/partner-stat.js#L80)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There seems to be a flaw in the logic.

remained ---> remaining
</blockquote></details>

Done.
___
*[src/util/partner-stat.js, line 268 at r3](https://reviewable.io/reviews/saltastro/tacprocess/102#-LriDTbr2I2HsGEVynPU:-LrnfhmM9ycj4jpIP4B5:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/70b8a426c9e5d02ecc2bfb75b8563bf0de86b305/src/util/partner-stat.js#L268)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think you should apply the factor 1/43 here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-10-22 15:14 UTC, hettlage reviewed
> Reviewed 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: all files reviewed, 2 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2019-10-23 17:16 UTC, hettlage approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/102)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2019-10-23 17:16 UTC, merged