new Stats
saltastro/tacprocess pull request #135
Opened 2020-01-22 14:40 UTC by Eb-Zeero

2020-01-23 14:23 UTC, hettlage requested changes
> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/actions/data-actions.js, line 98 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGTXgaCQ1nCjOxzV5r:-LzGTXgbBPSW3y2OUsjW:bmhi546) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/actions/data-actions.js#L98)):*
> ```JavaScript
>         dispatch(totalObservation(calculateTotalObservation(data[ 10 ])))
>         dispatch(fetchTimeBreakdownPass(data[ 11 ], currentSemester), currentSemester)
>         dispatch(fetchStatisticsPass(data[ 12 ]))
> ```

This is just an observation and not a change request:

The amount of data queried and the use of indexes is slightly worrisome.
___
*[src/api/graphQL.js, line 321 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGUcoA6W1lx3nEeCLR:-LzGUcoB3h74m-YeshHA:bf1stj9) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L321)):*
> ```JavaScript
>             salticam
>           }
>           timeRequestedPerRssDetector{
> ```

The name "timeRequestedPerRssDetector" should really be "timeRequestedPerRssDetectorMode".

Analogous remarks apply to other names in this file.
___
*[src/api/graphQL.js, line 347 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGV8tK9Aj1tfL7DUdy:-LzGV8tLB0_scoYhRa6l:bx0f65k) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L347)):*
> ```JavaScript
>             slotMode
>           }
>           timeRequestedPerHrsExposure{
> ```

The name should be timeRequestedPerHrsResolution
___
*[src/api/graphQL.js, line 354 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGVWZP8TDVeBzWDX6e:-LzGVWZP8TDVeBzWDX6f:b-d57aqi) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L354)):*
> ```JavaScript
>             intCalFibre
>           }
>           numberOfConfigurationsPerHrsExposure{
> ```

The name should be numberOfConfigurationsPerHrsResolution
___
*[src/api/graphQL.js, line 382 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGW3LO2AOZ4R4VOVzn:-LzGW3LO2AOZ4R4VOVzo:b-7hhe2y) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L382)):*
> ```JavaScript
>           }
>         }
>         observingConditions{
> ```

No change request, but an observation:

It seems that the structure is a bit inconsistent. (Now you group requested time and number of [confis/proposals] together, previously you didn't.
___
*[src/api/graphQL.js, line 386 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGWfG46QMdJflfgmfw:-LzGWfG46QMdJflfgmfx:bf1z0r) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L386)):*
> ```JavaScript
>             timeRequested{
>               lessEqual1Dot5
>               lessEqual2
> ```

No change request, but an observation:

Names like this are ambiguous. This one could mean seeing <= 2 or 1.5 < seeing <= 2.
___
*[src/components/pages/PartnerStatPage.js, line 69 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGfmLs51pP907WPZYJ:-LzGfmLs51pP907WPZYK:b6ycomk) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/PartnerStatPage.js#L69)):*
> ```JavaScript
>         <div className='stat-wrapper'>
>           <TransparencyDistribution
>             observingConditionsClouds={ observingConditions.clouds }
> ```

The name could be something simpler like "distribution".
___
*[src/components/pages/PartnerStatPage.js, line 71 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGg2-W7N9vl1lrACDs:-LzGg2-W7N9vl1lrACDt:byucke0) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/PartnerStatPage.js#L71)):*
> ```JavaScript
>             observingConditionsClouds={ observingConditions.clouds }
>           />
>           <ObservingStatisticsTransparency
> ```

The component names leave you wondering why you have two components/
___
*[src/components/pages/StatisticsPage.js, line 88 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGhzLIDyQDdri2Gv0p:-LzGhzLIDyQDdri2Gv0q:b-vq97nk) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/StatisticsPage.js#L88)):*
> ```JavaScript
>         <h2>Seeing requests</h2>
>         <div className='stat-wrapper-center'>
>           <ObservingStatisticsSeeing observingConditionsSeeing={ observingConditions.seeing }/>
> ```

A simpler name could be chosen perhaps.

This comment applies to other property names in this file as well.
___
*[src/components/plots/HrsModeDistribution.js, line 7 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGjpET0MOwJaVCyYas:-LzGjpET0MOwJaVCyYat:b-a7o90y) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/plots/HrsModeDistribution.js#L7)):*
> ```JavaScript
> 
> const HrsModeDistribution = ({timeRequestedPerHrsExposure}) => {
>   const exposureModes = [
> ```

Theese are not exposure modes, but rather resolutions or maybe resolution modes.
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 23 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmI9x5xt3H-VsPgGt:-LzGmI9x5xt3H-VsPgGu:b-n1ij6i) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L23)):*
> ```JavaScript
>           <tr>
>             <td>Max Seeing <br /> &#x2266; 1.5 </td>
>             <td>{ (timeRequested.lessEqual1Dot5).toFixed(2) }</td>
> ```

Given that you repeat this four times, you should consider using a constant instead of '2'.
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGm2DJAmCOrcxVTSDx:-LzGm2DKChwSbEkpIGzh:b-ue57t9) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L25)):*
> ```JavaScript
>             <td>{ (timeRequested.lessEqual1Dot5).toFixed(2) }</td>
>             <td>{ numberOfProposals.lessEqual1Dot5 }</td>
>             <td>{ ((timeRequested.lessEqual1Dot5/totalReqTime)*100).toFixed(1) }</td>
> ```

Given that you repeat the calculation four times, you should consider using a helper function.
___
*[src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js, line 23 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmZEH6pPha6MHjUrd:-LzGmZEH6pPha6MHjUre:b87n8ye) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js#L23)):*
> ```JavaScript
>           <tr>
>             <td>Clear</td>
>             <td>{ observingConditionsClouds.timeRequested.clear.toFixed(2) }</td>
> ```

Given that you have the same code four times, you might consider using constant instead of 2.
___
*[src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmqlG2_9PH0vf8YHJ:-LzGmqlG2_9PH0vf8YHK:b-c3r7uv) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js#L25)):*
> ```JavaScript
>             <td>{ observingConditionsClouds.timeRequested.clear.toFixed(2) }</td>
>             <td>{ observingConditionsClouds.nu [...]

2020-01-24 14:49 UTC, Eb-Zeero reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135#-:-LzN0wE33bHbWDDMrA1t:bnfp4nl)* status: all files reviewed, 17 unresolved discussions (waiting on @hettlage)

___
*[src/actions/data-actions.js, line 98 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGTXgaCQ1nCjOxzV5r:-LzMiyGsELblbZ28N5lw:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/actions/data-actions.js#L98)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This is just an observation and not a change request:

The amount of data queried and the use of indexes is slightly worrisome.
</blockquote></details>

Done.
___
*[src/api/graphQL.js, line 321 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGUcoA6W1lx3nEeCLR:-LzMk0giElNuLy9NuHPi:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L321)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name "timeRequestedPerRssDetector" should really be "timeRequestedPerRssDetectorMode".

Analogous remarks apply to other names in this file.
</blockquote></details>

Done.
___
*[src/api/graphQL.js, line 347 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGV8tK9Aj1tfL7DUdy:-LzMk24L32p_cPEBbxzt:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L347)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name should be timeRequestedPerHrsResolution
</blockquote></details>

Done.
___
*[src/api/graphQL.js, line 354 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGVWZP8TDVeBzWDX6e:-LzMk3Zi27F9qMfueirr:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L354)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name should be numberOfConfigurationsPerHrsResolution
</blockquote></details>

Done.
___
*[src/api/graphQL.js, line 382 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGW3LO2AOZ4R4VOVzn:-LzN0tuCAG6vL8z-IXya:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L382)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No change request, but an observation:

It seems that the structure is a bit inconsistent. (Now you group requested time and number of [confis/proposals] together, previously you didn't.
</blockquote></details>

Done.
___
*[src/api/graphQL.js, line 386 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGWfG46QMdJflfgmfw:-LzHvbRU95iI77Qou8TX:b-5452j4) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L386)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

No change request, but an observation:

Names like this are ambiguous. This one could mean seeing <= 2 or 1.5 < seeing <= 2.
</blockquote></details>

wording would have been long
___
*[src/components/pages/PartnerStatPage.js, line 69 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGfmLs51pP907WPZYJ:-LzN05gZDsINwtSI5Xpw:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/PartnerStatPage.js#L69)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The name could be something simpler like "distribution".
</blockquote></details>

Done.
___
*[src/components/pages/PartnerStatPage.js, line 71 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGg2-W7N9vl1lrACDs:-LzHvnOK8Kk4Kgw2cn1k:b6fjq65) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/PartnerStatPage.js#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The component names leave you wondering why you have two components/
</blockquote></details>

other table other histrogram
___
*[src/components/pages/StatisticsPage.js, line 88 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGhzLIDyQDdri2Gv0p:-LzMq_4B-evYKzhtvKwS:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/StatisticsPage.js#L88)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

A simpler name could be chosen perhaps.

This comment applies to other property names in this file as well.
</blockquote></details>

Done.
___
*[src/components/plots/HrsModeDistribution.js, line 7 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGjpET0MOwJaVCyYas:-LzMsVuW3PnxDhlX55BK:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/plots/HrsModeDistribution.js#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Theese are not exposure modes, but rather resolutions or maybe resolution modes.
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 23 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmI9x5xt3H-VsPgGt:-LzMwCJkBM4G_ji0AD3q:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that you repeat this four times, you should consider using a constant instead of '2'.
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGm2DJAmCOrcxVTSDx:-LzMxaim9DVZMUGqgmBn:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that you repeat the calculation four times, you should consider using a helper function.
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js, line 23 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmZEH6pPha6MHjUrd:-LzMyR0OCwCDAHNqM7N9:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js#L23)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that you have the same code four times, you might consider using constant instead of 2.
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmqlG2_9PH0vf8YHJ:-LzMySwa65Mu0k8D1x6g:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given that you use the same calculation four times, you might consider using a helper function.

Also, this helper function might be shared by other files.

</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ProposalsCountTable.js, line 45 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGodsx5E_s3YAMAIzq:-LzMybum2pGVYN8zGwER:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e [...]

2020-01-27 08:03 UTC, hettlage requested changes
> Reviewed 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/types.js, line 3 at r2](https://reviewable.io/reviews/saltastro/tacprocess/135#-Lz_uZKwDMj6qQHv8bw6:-Lz_uZKwDMj6qQHv8bw7:b-x6x6ez) ([raw file](https://github.com/saltastro/tacprocess/blob/3820c06a01ec17828968c9018096736aaf22ae9c/src/types.js#L3)):*
> ```JavaScript
> export const API_BASE_URL = process.env.REACT_APP_API_BASE_URL
> export const SALT_SERVER_API_URL = process.env.REACT_APP_SALT_SERVER_API_URL
>  export const FRACTION_DIGITS_2 = 2
> ```

See comment in the file using these constants.
___
*[src/api/graphQL.js, line 386 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGWfG46QMdJflfgmfw:-Lz_v6dI3S1Zwwf3PE3m:bklbg5p) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L386)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

wording would have been long
</blockquote></details>

Yes. But maybe this points to the interesting question whether the API could be improved... :/
___
*[src/components/pages/PartnerStatPage.js, line 71 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGg2-W7N9vl1lrACDs:-Lz_vpgXDeZqj2M9jvKH:b-6rhg7y) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/PartnerStatPage.js#L71)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

other table other histrogram
</blockquote></details>

 Maybe the names should reflect that?
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGm2DJAmCOrcxVTSDx:-Lz_wNDU2QFj15EoipCS:b1mpc7j) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L25)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes. But if you replace them with global constants called FRACTION_DIGITS_1/2, you don't gain anything. :)
___
*[src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmqlG2_9PH0vf8YHJ:-Lz_xiVt6HAVy3w9g3XC:bb4vq9w) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js#L25)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uhm, really? :)
___
*[src/components/tables/statisticsTables/ProposalsCountTable.js, line 45 at r2](https://reviewable.io/reviews/saltastro/tacprocess/135#-Lz_y3GqCLRtSX9m31Ch:-Lz_y3GqCLRtSX9m31Ci:b-t43zw5) ([raw file](https://github.com/saltastro/tacprocess/blob/3820c06a01ec17828968c9018096736aaf22ae9c/src/components/tables/statisticsTables/ProposalsCountTable.js#L45)):*
> ```JavaScript
>           </tr>
>           <tr>
>             <td>Thesis proposal </td>
> ```

Better: Proposals used for a thesis
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 22 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGqPBQ7RdqkDJaAbm-:-Lz_yG-Y7qECCmT79KnM:b-d7q9aw) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L22)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

we get something like 100.00% which looks ugly helper will do
</blockquote></details>

But you could improve the handler: rounded(...) would look better than removeDot00(...toFixed(2))
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/135#-Lza0LBZ7ycbRQH3IbVF:-Lza0LBZ7ycbRQH3IbVG:b-dorxb4) ([raw file](https://github.com/saltastro/tacprocess/blob/3820c06a01ec17828968c9018096736aaf22ae9c/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L32)):*
> ```JavaScript
>           partnerSummaryStat.summary.allocatedTime.p0 + partnerSummaryStat.summary.allocatedTime.p1).toFixed(2)
>         ) }%</td>
>       <td>{ removeDot00(calculatePercentage(partnerSummaryStat.summary.observedTime.p2, partnerSummaryStat.summary.allocatedTime.p2).toFixed(2)) }%</td>
> ```

calculatePercentage can be replaced with the getPercentage utility function, can't it?


<!-- Sent from Reviewable.io -->

2020-01-27 09:43 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: 24 of 32 files reviewed, 17 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/components/pages/PartnerStatPage.js, line 71 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGg2-W7N9vl1lrACDs:-LzaLyWJ5BJnHYuPOzlV:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/pages/PartnerStatPage.js#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

 Maybe the names should reflect that?
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGm2DJAmCOrcxVTSDx:-LzaMclh4hR0oKfrU97y:b-x8jvk5) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes. But if you replace them with global constants called FRACTION_DIGITS_1/2, you don't gain anything. :)
</blockquote></details>

can we discuss this
___
*[src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js, line 25 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGmqlG2_9PH0vf8YHJ:-LzaNFiO-c9eRFjCr1DZ:b-o0in8u) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/statisticsTables/ObservingStatisticsTransparacy.js#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Uhm, really? :)
</blockquote></details>

sorry did it on one and not the other.


<!-- Sent from Reviewable.io -->

2020-01-27 10:22 UTC, hettlage reviewed
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)



<!-- Sent from Reviewable.io -->

2020-01-27 10:54 UTC, hettlage reviewed
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)



<!-- Sent from Reviewable.io -->

2020-01-27 11:07 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: 30 of 33 files reviewed, 12 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/components/tables/statisticsTables/ProposalsCountTable.js, line 45 at r2](https://reviewable.io/reviews/saltastro/tacprocess/135#-Lz_y3GqCLRtSX9m31Ch:-LzacpwI3H5U8k87qQt-:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/3820c06a01ec17828968c9018096736aaf22ae9c/src/components/tables/statisticsTables/ProposalsCountTable.js#L45)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Better: Proposals used for a thesis
</blockquote></details>

Done.
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 22 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGqPBQ7RdqkDJaAbm-:-LzadCEF2ZxX0w9LkOu2:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you could improve the handler: rounded(...) would look better than removeDot00(...toFixed(2))
</blockquote></details>

Done.
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/135#-Lza0LBZ7ycbRQH3IbVF:-LzaeBcM6m3HC3MJkLal:bb29iw3) ([raw file](https://github.com/saltastro/tacprocess/blob/3820c06a01ec17828968c9018096736aaf22ae9c/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

calculatePercentage can be replaced with the getPercentage utility function, can't it?
</blockquote></details>

It can and Done.


<!-- Sent from Reviewable.io -->

2020-01-27 11:11 UTC, hettlage requested changes
> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 22 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGqPBQ7RdqkDJaAbm-:-LzagGmyAaI-8TtPVjwy:bs4f0vb) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L22)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

But I meant to include the toFixed in the helper.

BTW, note that no constants are used for the number of digits in this fie.


<!-- Sent from Reviewable.io -->

2020-02-04 11:21 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: 28 of 33 files reviewed, 11 unresolved discussions (waiting on @hettlage)

___
*[src/types.js, line 3 at r2](https://reviewable.io/reviews/saltastro/tacprocess/135#-Lz_uZKwDMj6qQHv8bw6:-M-ErkFK8t1sbVYqiIvm:b-x7ucks) ([raw file](https://github.com/saltastro/tacprocess/blob/3820c06a01ec17828968c9018096736aaf22ae9c/src/types.js#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

See comment in the file using these constants.
</blockquote></details>


only -> LOW_PRECISION left  HIGH_PRECISION not used any more
___
*[src/api/graphQL.js, line 386 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGWfG46QMdJflfgmfw:-M-Evf97Be8L0RUwHLdo:b-uq5wnl) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/api/graphQL.js#L386)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Yes. But maybe this points to the interesting question whether the API could be improved... :/
</blockquote></details>

wont fix on this version
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 22 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGqPBQ7RdqkDJaAbm-:-M-ErYdL-OkrE2Hfhur0:bp0t32o) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But I meant to include the toFixed in the helper.

BTW, note that no constants are used for the number of digits in this fie.
</blockquote></details>

all fixed


<!-- Sent from Reviewable.io -->

2020-02-04 19:28 UTC, hettlage requested changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135#-:-M-Gegar6Y-RP0K2jFd3:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js, line 21 at r6](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-GdO7v-5wWMtz4Y-Id:-M-GdO7v-5wWMtz4Y-Ie:b-52rtu3) ([raw file](https://github.com/saltastro/tacprocess/blob/178dba893e7a2b96d71f1b8019b3eafd59cba987/src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js#L21)):*
> ```JavaScript
>           <tr>
>             <td>Science</td>
>             <td>{rounded(timeBreakdown.science / 3600)}</td>
> ```

Shouldn't this be toFixed(LOW_RESOLUTION) instead of an integer? (Same for the following code, of course.)
___
*[src/components/tables/statisticsTables/ProposalsCountTable.js, line 59 at r6](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-GeCXW-PK7fWIxN05I:-M-GeCXW-PK7fWIxN05J:b-x7t1n3) ([raw file](https://github.com/saltastro/tacprocess/blob/178dba893e7a2b96d71f1b8019b3eafd59cba987/src/components/tables/statisticsTables/ProposalsCountTable.js#L59)):*
> ```JavaScript
> 
> ProposalCountTable.propTypes = {
>   proposal: propTypes.object.isRequired
> ```

Now here proposalStatistics would be the better name choice...
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 22 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGqPBQ7RdqkDJaAbm-:-M-GeWR27aNbMtwCvA7_:b1but7k) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L22)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

all fixed
</blockquote></details>

Just a question: Should 2 be HIGH_PRECISION instead?


<!-- Sent from Reviewable.io -->

2020-02-05 13:28 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r7.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/components/tables/statisticsTables/AvailableTimePerPartner.js, line 24 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KUHzl0xIxlAAo3H29:-M-KUHzl0xIxlAAo3H2A:b9opgsc) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/AvailableTimePerPartner.js#L24)):*
> ```JavaScript
>             <td>Priority 0 & 1</td>
>             <td>{ rounded(availableTime.p0p1) }</td>
>             <td style={ correctAllocations.p0p1 ? goodTime : badTime }><label>{ rounded(parseFloat(allocatedTotals.p0/(60*60)) + parseFloat(allocatedTotals.p1/(60*60)) || 0) }</label></td>
> ```

Maybe include at least one fractional digit?
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 25 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KUb_TALLUO3o6Fg1S:-M-KUb_TALLUO3o6Fg1T:b8klkwh) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L25)):*
> ```JavaScript
>           <tr>
>             <td>Max Seeing <br /> &#x2266; 1.5 </td>
>             <td>{ rounded(timeRequested.lessEqual1Dot5) }</td>
> ```

If (!) the requested time is in hours, yiou might consider including one fractional digit.
___
*[src/components/tables/statisticsTables/PartnerTimeTable.js, line 36 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KV0v17-DcUw0DJUJC:-M-KV0v17-DcUw0DJUJD:b-tvtu0n) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/PartnerTimeTable.js#L36)):*
> ```JavaScript
>             <td>Actual time available</td>
> 
>             <td>{rounded(allocatedTimeSum/1.4) } </td>
> ```

You should explain the factor 1.4.
___
*[src/components/tables/statisticsTables/PartnerTimeTable.js, line 41 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KVC6O3u8yuxfgcdZe:-M-KVC6O3u8yuxfgcdZf:bt6gmev) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/PartnerTimeTable.js#L41)):*
> ```JavaScript
>           <tr>
>             <td>Requested time (P0 to P3) </td>
>             <td>{rounded(total/3600)}</td>
> ```

You might consider having one fractional digit.
___
*[src/util/index.js, line 480 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KVnDv3HpOwKWlTTzT:-M-KVnDw3HISpMqZUefT:b-97yczt) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/util/index.js#L480)):*
> ```JavaScript
>     return 0
>   }
>   return number.toFixed(fixTo).replace(/\.00$/, '')
> ```

If you include the number of fractional digits as an argument, you should update the regular expression:

new RegExp(`\\.0{${fixTo}}$') or something like that.


<!-- Sent from Reviewable.io -->

2020-02-06 07:42 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 8 unresolved discussions (waiting on @Eb-Zeero and @hettlage)

___
*[src/components/tables/statisticsTables/AvailableTimePerPartner.js, line 24 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KUHzl0xIxlAAo3H29:-M-OPmcQErRxMsa6FZAU:b-2rhnyy) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/AvailableTimePerPartner.js#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe include at least one fractional digit?
</blockquote></details>

it is rounded to 2
___
*[src/components/tables/statisticsTables/ObservingStatisticsSeeing.js, line 25 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KUb_TALLUO3o6Fg1S:-M-OPvLBB17KApBq1qVk:b-en3l3w) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/ObservingStatisticsSeeing.js#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

If (!) the requested time is in hours, yiou might consider including one fractional digit.
</blockquote></details>

it is rounded to 2
___
*[src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js, line 21 at r6](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-GdO7v-5wWMtz4Y-Id:-M-OQ-JW2JILO1wHxpvy:b-2rhnyy) ([raw file](https://github.com/saltastro/tacprocess/blob/178dba893e7a2b96d71f1b8019b3eafd59cba987/src/components/tables/statisticsTables/ObservingStatisticsTimeBreakdown.js#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't this be toFixed(LOW_RESOLUTION) instead of an integer? (Same for the following code, of course.)
</blockquote></details>

it is rounded to 2
___
*[src/components/tables/statisticsTables/PartnerTimeTable.js, line 36 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KV0v17-DcUw0DJUJC:-M-OQ5jI4lv53ETXVhzX:bxurhr2) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/PartnerTimeTable.js#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You should explain the factor 1.4.
</blockquote></details>

I do not know why but the value was divided by the same factor before
___
*[src/components/tables/statisticsTables/PartnerTimeTable.js, line 41 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KVC6O3u8yuxfgcdZe:-M-OQC9Q0P4WvNvzFOEh:b-2rhnyy) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/PartnerTimeTable.js#L41)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You might consider having one fractional digit.
</blockquote></details>

it is rounded to 2
___
*[src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js, line 22 at r1](https://reviewable.io/reviews/saltastro/tacprocess/135#-LzGqPBQ7RdqkDJaAbm-:-M-OQHkc19qTxHtizkAO:b-2rhnyy) ([raw file](https://github.com/saltastro/tacprocess/blob/606e1512846a0d7b859e8cf0cb71be47928f7dc0/src/components/tables/tablesComponents/PartnerSummaryStatTableRow1.js#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Just a question: Should 2 be HIGH_PRECISION instead?
</blockquote></details>

it is rounded to 2
___
*[src/util/index.js, line 480 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KVnDv3HpOwKWlTTzT:-M-ORclADQXo9Pe2wS6e:b-sy38up) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/util/index.js#L480)):*
> \.0{${fixTo}}$
I only need to fix to  N and remove .00 if that can be
 


<!-- Sent from Reviewable.io -->

2020-02-06 07:44 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 8 unresolved discussions (waiting on @hettlage)

___
*[src/components/tables/statisticsTables/ProposalsCountTable.js, line 59 at r6](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-GeCXW-PK7fWIxN05I:-M-OSKh8EXWih5v0ogjC:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/178dba893e7a2b96d71f1b8019b3eafd59cba987/src/components/tables/statisticsTables/ProposalsCountTable.js#L59)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Now here proposalStatistics would be the better name choice...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-06 09:25 UTC, hettlage reviewed
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 7 unresolved discussions (waiting on @hettlage)



<!-- Sent from Reviewable.io -->

2020-02-06 09:33 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[src/components/tables/statisticsTables/AvailableTimePerPartner.js, line 24 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KUHzl0xIxlAAo3H29:-M-OpacT8BdaXsgReHPc:byp7lk1) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/AvailableTimePerPartner.js#L24)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it is rounded to 2
</blockquote></details>

Ah, right, my bad. But in my defence, "round" is associated with rounding to the nearest _integer_... :-)
___
*[src/components/tables/statisticsTables/PartnerTimeTable.js, line 36 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KV0v17-DcUw0DJUJC:-M-Oq2nkC1YcYv9NNSzv:b2pknlh) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/PartnerTimeTable.js#L36)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

I do not know why but the value was divided by the same factor before
</blockquote></details>

Maybe at least add ac TODO to find out?
___
*[src/util/index.js, line 480 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KVnDv3HpOwKWlTTzT:-M-Op56t0D4gE36mNh9_:bh9aa8t) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/util/index.js#L480)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

> \.0{${fixTo}}$
I only need to fix to  N and remove .00 if that can be
 
</blockquote></details>

But rounded(5.000001, 4) would give you 5.00, wouldn't it, which is not what you wanted (I guess)?


<!-- Sent from Reviewable.io -->

2020-02-06 11:00 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[src/components/tables/statisticsTables/AvailableTimePerPartner.js, line 24 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KUHzl0xIxlAAo3H29:-M-P88T9Cve-Iu3cuObF:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/AvailableTimePerPartner.js#L24)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Ah, right, my bad. But in my defence, "round" is associated with rounding to the nearest _integer_... :-)
</blockquote></details>

Done.
___
*[src/components/tables/statisticsTables/PartnerTimeTable.js, line 36 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KV0v17-DcUw0DJUJC:-M-P919_8ZqU-h-0FC2A:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/components/tables/statisticsTables/PartnerTimeTable.js#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe at least add ac TODO to find out?
</blockquote></details>

Done.
___
*[src/util/index.js, line 480 at r7](https://reviewable.io/reviews/saltastro/tacprocess/135#-M-KVnDv3HpOwKWlTTzT:-M-P8Am85Ljtc0ou3D3L:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/88aa02534e5de416872fe4b7ee16cd5bd97114f2/src/util/index.js#L480)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But rounded(5.000001, 4) would give you 5.00, wouldn't it, which is not what you wanted (I guess)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-02-07 10:51 UTC, hettlage approved these changes
> Reviewed 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/135)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-02-07 10:52 UTC, merged