Making it possible to add and remove TAC Chair
saltastro/tacprocess pull request #202
Opened 2024-03-25 14:00 UTC by Eb-Zeero

2024-03-26 08:32 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 3 unresolved discussions (waiting on @Eb-Zeero)

___
*[`src/actions/timeAllocationActions.js` line 67 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-Ntthiy44L9f1yj9BjsH:-Ntthiy5EJ2sSkiVfd_2:bogu8f4) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/actions/timeAllocationActions.js#L67)):*
> ```JavaScript
> })
> 
> export const makeChair = (member, partner) => ({
> ```

`makeChair` suggests that you make the member a chair, but from what I can see, you use the method for both making and removing chairs. In line wit the rest of the file yiu might consider having separate methods.

In case of a single method, there should be an argument deciding whether to add or remove a chair (rather than setting it on the passed member instance).
___
*[`src/components/tables/TacMemberEditTable.js` line 36 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-NttjQK73MUH-RP_SDCD:-NttjQK73MUH-RP_SDCE:b-hbhkmk) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/components/tables/TacMemberEditTable.js#L36)):*
> ```JavaScript
>                     </td>
>                   <td>
>                     {!m.isTacChair && <button onClick={ () => makeChair(m, p, true) }> Make Chair</button>}
> ```

Wouldn't it be more natural to have a checkbox, at least if you still have to click a save button?
___
*[`src/reducers/tac.js` line 180 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-NttsYIdECWln6qeP-am:-NttsYIdECWln6qeP-an:b-ujz71d) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/reducers/tac.js#L180)):*
> ```JavaScript
>   }
>   case MAKE_CHAIR: {
>     if (!state.newMembers[ action.payload.partner ]){
> ```

This code looks odd to me. Can we chat about it (and the surrounding code)?


<!-- Sent from Reviewable.io -->

2024-03-28 06:27 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @hettlage)

___
*[`src/actions/timeAllocationActions.js` line 67 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-Ntthiy44L9f1yj9BjsH:-Nu2jReOAxs6rjcs5Hsd:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/actions/timeAllocationActions.js#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`makeChair` suggests that you make the member a chair, but from what I can see, you use the method for both making and removing chairs. In line wit the rest of the file yiu might consider having separate methods.

In case of a single method, there should be an argument deciding whether to add or remove a chair (rather than setting it on the passed member instance).
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 36 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-NttjQK73MUH-RP_SDCD:-Nu2jTvH-4k2aATxZsxe:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/components/tables/TacMemberEditTable.js#L36)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it be more natural to have a checkbox, at least if you still have to click a save button?
</blockquote></details>

Done.
___
*[`src/reducers/tac.js` line 180 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-NttsYIdECWln6qeP-am:-Nu2jVQe6gru4CXImxjY:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/reducers/tac.js#L180)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This code looks odd to me. Can we chat about it (and the surrounding code)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-28 08:25 UTC, hettlage requested changes

2024-03-28 08:25 UTC, hettlage commented on .eslintrc
> +    "template-curly-spacing": [0, "always"],
I have the suspicion that this configuration is not correct; see https://eslint.org/docs/latest/rules/template-curly-spacing.

2024-03-28 08:25 UTC, hettlage commented on src/actions/timeAllocationActions.js
> +  SAVE_MEMBERS, UPDATE_MEMBER
This line suggests that Prettier hasn't been run...

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +                    { m.isTacChair ? 'Remove As Chair' : 'Make Chair' }
a) This should be in a label element.

b) The text should be "Is a TAC Chair" irrespective of `m.isTacChair`.

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +                <tr key={ `${b}b` }>
You shouldn't use the index as the key. Quoting from https://react.dev/learn/rendering-lists#rules-of-keys:

"You might be tempted to use an item’s index in the array as its key. In fact, that’s what React will use if you don’t specify a key at all. But the order in which you render items will change over time if an item is inserted, deleted, or if the array gets reordered. Index as a key often leads to subtle and confusing bugs.

Similarly, do not generate keys on the fly, e.g. with key={Math.random()}. This will cause keys to never match up between renders, leading to all your components and DOM being recreated every time. Not only is this slow, but it will also lose any user input inside the list items. Instead, use a stable ID based on the data."

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +              (newMembers[p] || []).sort(compareByFirstName).map((m, c) => (
Wouldn't it be more natural to sort by last name?

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +              { (newMembers[p] || []).length > 0 && <th colSpan={4}>New or Updated Members</th>}
Shouldn't the condition `(newMembers[p] || []).length > 0` rather be applied to the surrounding tr element?

For consistency, "New or Updated Members" should rather read "Members to Add or Update".

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +                <tr key={ `${c}c` } className="new-tac-row">
You shouldn't use the index as the key.

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +                    /> { m.isTacChair ? 'Remove As Chair' : 'Make Chair' }</td>
a) This should be in a label element.

b) The text should be "Is a TAC Chair" irrespective of m.isTacChair.

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +              { (removedMembers[p] || []).length > 0 && <th colSpan={4}>Members to Remove</th> }
Shouldn't the condition `(removedMembers[p] || []).length > 0` rather be applied to the surrounding tr element?

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +                  <tr key={`${c}c`} className="removed-tac-row">
You shouldn't use the index as the key.

2024-03-28 08:25 UTC, hettlage commented on src/components/tables/TacMemberEditTable.js
> +                removedMembers[p] || []).sort(compareByFirstName).map((m, c) => (
Wouldn't it be more natural to sort by last name?

2024-04-05 06:08 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: 2 of 9 files reviewed, 14 unresolved discussions (waiting on @hettlage)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-NudJQGT-Ov4oTvNcLiX:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I have the suspicion that this configuration is not correct; see https://eslint.org/docs/latest/rules/template-curly-spacing.
</blockquote></details>

Done.
___
*[`src/actions/timeAllocationActions.js` line 13 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542444067:-NudJYKq8RMruGAZNTRE:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/actions/timeAllocationActions.js#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This line suggests that Prettier hasn't been run...
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 26 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542456673:-NudL7vL0CsyZtBGgLBA:b-2ma0aw) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't use the index as the key. Quoting from https://react.dev/learn/rendering-lists#rules-of-keys:

"You might be tempted to use an item’s index in the array as its key. In fact, that’s what React will use if you don’t specify a key at all. But the order in which you render items will change over time if an item is inserted, deleted, or if the array gets reordered. Index as a key often leads to subtle and confusing bugs.

Similarly, do not generate keys on the fly, e.g. with key={Math.random()}. This will cause keys to never match up between renders, leading to all your components and DOM being recreated every time. Not only is this slow, but it will also lose any user input inside the list items. Instead, use a stable ID based on the data."
</blockquote></details>

my data doesn't have ID.. this will require a backend change.

that is why I recreate this array everytime a member is added or removed 
___
*[`src/components/tables/TacMemberEditTable.js` line 38 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542451363:-NudM5vo583o2LMCrYr4:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a) This should be in a label element.

b) The text should be "Is a TAC Chair" irrespective of `m.isTacChair`.
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 49 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466378:-NudMd4rECgG79Pm0aGw:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L49)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the condition `(newMembers[p] || []).length > 0` rather be applied to the surrounding tr element?

For consistency, "New or Updated Members" should rather read "Members to Add or Update".
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 52 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542458485:-NudNU_g-u2A3sPv85w5:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it be more natural to sort by last name?
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 53 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466469:-NudNW1e-DLLIUq30smO:b-1xg0or) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't use the index as the key.
</blockquote></details>

Members do not have ID this will require a backend change
___
*[`src/components/tables/TacMemberEditTable.js` line 64 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466849:-NudNvzY1ks-4wMaU6Hq:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a) This should be in a label element.

b) The text should be "Is a TAC Chair" irrespective of m.isTacChair.
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 71 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542470179:-NudNxG75NnACsMu1rM_:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the condition `(removedMembers[p] || []).length > 0` rather be applied to the surrounding tr element?
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 75 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542498886:-NudNypHEb8CTN10FXrt:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L75)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wouldn't it be more natural to sort by last name?
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 76 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542471728:-NudO6U19wc_Y-8ze2Az:b5ax70v) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You shouldn't use the index as the key.
</blockquote></details>

this will require backend change if this has high enough priority I can Implement


<!-- Sent from Reviewable.io -->

2024-04-05 12:46 UTC, hettlage requested changes
> Reviewed 2 of 6 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 9 unresolved discussions (waiting on @Eb-Zeero)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-NuiEsdq3reO__NQr3gz:bub3owa) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Uhm, the previous version suggested that you *want* to have errors, but this suggests you do not want to errors?
___
*[`src/types.js` line 71 at r3](https://reviewable.io/reviews/saltastro/tacprocess/202#-NuiF6he91yPp_Evmadn:-NuiF6he91yPp_Evmado:bmyisac) ([raw file](https://github.com/saltastro/tacprocess/blob/f56bc9c1064a0bb7ebb705cb90871828317a9b40/src/types.js#L71)):*
> ```JavaScript
> export const ADD_NEW_MEMBER = 'ADD_NEW_MEMBER'
> export const REMOVE_MEMBER = 'REMOVE_MEMBER'
> export const UPDATE_MEMBER = 'MAKE_CHAIR'
> ```

I'd suggest to change the value of the constant (to `UPDATE_MEMBER`) as well.
___
*[`src/actions/timeAllocationActions.js` line 67 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-Ntthiy44L9f1yj9BjsH:-NuiFYViDuyIiRaElYaT:b6ev0db) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/actions/timeAllocationActions.js#L67)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't think the comment has been addressed...
___
*[`src/components/tables/TacMemberEditTable.js` line 26 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542456673:-NuiFtDi2lEHX62rUdTy:b-1gvfip) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

my data doesn't have ID.. this will require a backend change.

that is why I recreate this array everytime a member is added or removed
</blockquote></details>

But you have the name and surname...
___
*[`src/components/tables/TacMemberEditTable.js` line 38 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542451363:-NuiHG9G6CDQoI6k3QPU:bxmxe2u) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L38)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry... and the label element should be associated with the corresponding input element.
___
*[`src/components/tables/TacMemberEditTable.js` line 53 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466469:-NuiHcAV6EUpMhAEdzOy:bxuchut) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L53)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Members do not have ID this will require a backend change
</blockquote></details>

But you have the name and surname... :-)
___
*[`src/components/tables/TacMemberEditTable.js` line 64 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466849:-NuiHjGA7ENJ0SS-tGjP:b-x9ewob) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L64)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry... and the label should be associated with the input element.
___
*[`src/components/tables/TacMemberEditTable.js` line 76 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542471728:-NuiGMewDBELc3SpLIfq:b96z5np) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L76)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

this will require backend change if this has high enough priority I can Implement
</blockquote></details>

But you have the name and surname. :-)
___
*[`src/util/filters.js` line 202 at r3](https://reviewable.io/reviews/saltastro/tacprocess/202#-NuiGr8b1_gIyL3KIsfd:-NuiGr8b1_gIyL3KIsfe:b-5fhmdh) ([raw file](https://github.com/saltastro/tacprocess/blob/f56bc9c1064a0bb7ebb705cb90871828317a9b40/src/util/filters.js#L202)):*
> ```JavaScript
>   const name1 = a.surname
>   const name2 = b.surname
>   if (name1 < name2) {
> ```

You could have used `localeCompare`, I think:

```
return a.surname.localeCompare(b.surname)
```


<!-- Sent from Reviewable.io -->

2024-04-08 11:34 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 9 unresolved discussions (waiting on @hettlage)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-Nux0IQODC4YibeC8uoo:b-ulnt1m) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Uhm, the previous version suggested that you *want* to have errors, but this suggests you do not want to errors?
</blockquote></details>

yes I know. but that rule was more pain than gain..
As sometimes there will be those templates on a single which are auto formatted by the IDE I have to space them manually every time and sometimes they are just a single variable.
will take it back to having errors
___
*[`src/types.js` line 71 at r3](https://reviewable.io/reviews/saltastro/tacprocess/202#-NuiF6he91yPp_Evmadn:-Nux2BhS-LEQjWc0qU4h:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/f56bc9c1064a0bb7ebb705cb90871828317a9b40/src/types.js#L71)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to change the value of the constant (to `UPDATE_MEMBER`) as well.
</blockquote></details>

Done.
___
*[`src/actions/timeAllocationActions.js` line 67 at r1](https://reviewable.io/reviews/saltastro/tacprocess/202#-Ntthiy44L9f1yj9BjsH:-NuxTQzRE3DEa87TyF4W:b-e7k68e) ([raw file](https://github.com/saltastro/tacprocess/blob/151d72f5eb1eba601be5a688a468e1c6fe529b41/src/actions/timeAllocationActions.js#L67)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think the comment has been addressed...
</blockquote></details>

We discussed this and agreed that renaming it to updateMember will work just fine.
in this case I do not need to specify if I am making or removing
___
*[`src/components/tables/TacMemberEditTable.js` line 26 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542456673:-Nux7rqv11SGfd8K4rzR:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you have the name and surname...
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 38 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542451363:-NuxT0-QAeLgaJS25IU5:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L38)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry... and the label element should be associated with the corresponding input element.
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 53 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466469:-Nux8A2--KclzecpGTv2:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L53)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you have the name and surname... :-)
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 64 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542466849:-NuxT1-r3MImXqUziziL:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L64)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Sorry... and the label should be associated with the input element.
</blockquote></details>

Done.
___
*[`src/components/tables/TacMemberEditTable.js` line 76 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542471728:-Nux8BZADLoDxr83OeLI:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/src/components/tables/TacMemberEditTable.js#L76)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But you have the name and surname. :-)
</blockquote></details>

Done.
___
*[`src/util/filters.js` line 202 at r3](https://reviewable.io/reviews/saltastro/tacprocess/202#-NuiGr8b1_gIyL3KIsfd:-NuxPBJHEyWqNt0BXU0D:b-896fix) ([raw file](https://github.com/saltastro/tacprocess/blob/f56bc9c1064a0bb7ebb705cb90871828317a9b40/src/util/filters.js#L202)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could have used `localeCompare`, I think:

```
return a.surname.localeCompare(b.surname)
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-08 17:50 UTC, hettlage requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-Nuyoq__8YhjIV57cx9C:b-6oafyt) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes I know. but that rule was more pain than gain..
As sometimes there will be those templates on a single which are auto formatted by the IDE I have to space them manually every time and sometimes they are just a single variable.
will take it back to having errors
</blockquote></details>

My comment was more about pointing out that the functionality had changed. If there is good reason not to have the rule, that's okay. (And now I have to ask again whether you are sure the configuration is correct?)


<!-- Sent from Reviewable.io -->

2024-04-09 06:41 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-Nv0_01p8MVeuSoGGmIr:b-y3do73) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

My comment was more about pointing out that the functionality had changed. If there is good reason not to have the rule, that's okay. (And now I have to ask again whether you are sure the configuration is correct?)
</blockquote></details>

yes they are correct. this is another way of doing it.


<!-- Sent from Reviewable.io -->

2024-04-09 09:48 UTC, hettlage requested changes
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 1 unresolved discussion (waiting on @Eb-Zeero)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-Nv1FKxX9xS1EGeCzFmA:blf4lbg) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

yes they are correct. this is another way of doing it.
</blockquote></details>

You win. But "warn" might still be easier to interpret than 1? (And I thought you don't want the rule?)


<!-- Sent from Reviewable.io -->

2024-04-10 11:30 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: all files reviewed, 1 unresolved discussion (waiting on @hettlage)

___
*[`.eslintrc` line 32 at r2](https://reviewable.io/reviews/saltastro/tacprocess/202#gh-1542443165:-Nv6kevj-tOgWAlfzWtW:b-7sczkj) ([raw file](https://github.com/saltastro/tacprocess/blob/062811bf2961d91054d407cbe025a1b79801d827/.eslintrc#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You win. But "warn" might still be easier to interpret than 1? (And I thought you don't want the rule?)
</blockquote></details>

I will deal with the rules on another PR
there is also a rule that `obj[0]` should be `obj[ 0 ]` which raises an error, not a warning. I don't know what I was thinking when I added these rules.


<!-- Sent from Reviewable.io -->

2024-04-10 19:26 UTC, hettlage approved these changes
> *[Reviewable](https://reviewable.io/reviews/saltastro/tacprocess/202)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Eb-Zeero)



<!-- Sent from Reviewable.io -->

2024-05-03 09:31 UTC, merged